### ISSUE TITLE
stockrom.zip

### ISSUE THREAD

**Issue by Andrei-Tanase** [NESPTchnology/Flyme6-devices-p8lite#1]
When you dumped the device with a specific command it did create some kind of stockrom.zip ?

**Comment by nespjin** [comment]
@XTutorials  yes,you can dump the device on recovery model with  ` ../tools/releasetools/ota_target_from_phone -r `

**Comment by nespjin** [comment]
I try to patch the miui base on aosp ,but it is bootloop and there have the log  http://nesp.1g7.net/blog/log.html @XTutorials

**Comment by Andrei-Tanase** [comment]
Yes, I have same issue, and I tried using AOKP, AOSP, and LOS 13 as a base.
